### ISSUE TITLE
Documentation, Expr and Stmt Generation and Organisation

### ISSUE THREAD

**Issue by ArrushC** [BlinkLang/BlinkLang#1]
I want to address 3 issues to this single issue that makes the src code unmaintainable:
- Documentation - It is vital that we should add documentation so when this project will be used by others, it will be easier to understand.
- GenerateAst - I feel that this file should be dropped and instead, have a new system that generates Expr and Stmt files. Currently I am thinking of adding `Generator` class. There may be more classes to add to make the new system.
- Organisation - To make this project more organised it should be considered adding packages and whatever necessary for organisation.

**Comment by Link-Byte** [comment]
- Documentation - I can fix this by making a README explaining what does 'x' do.
- GenerateAst - If you feel like there could be a lot more improvement to be done by adding a `Generator` class, go ahead. Currently, `GenerateAst` makes the `Expr` and `Stmt` files and 'dumps' them in the com\blink\Blink directory.
- Organization - This would have to be done with time since I don't want to affect the project in a bad way. We can look into what has to be done to make the Blink src code cleaner.

Thank you for your suggestions!

**Comment by ArrushC** [comment]
Alright. But as for documentation, additionally we should document the code as well i.e multiline comments, etc.

**Comment by Link-Byte** [comment]
Yes, that can be done fairly easily. Should be committed tomorrow.

**Comment by ArrushC** [comment]
Right now I am in school. After I come back, I will work on organisation a bit and generation. Perhaps I will do some documentation as well but it will be the guide/wiki.

Do you think making a video, guiding people on how to use Blink would be more efficient ?

**Comment by Link-Byte** [comment]
Alright, that's great Arrush, thank you. I can also work on a simple README and perhaps a couple of pages in the wiki.

I can make a quick video showing how to use the interpreter to evaluate expressions or to run a `.blink` file.

**Comment by Link-Byte** [comment]
On a side note, docs on how to use the Blink compiler have been added, and docs on syntax should be up soon!

**Comment by ArrushC** [comment]
It will be more better to do both. So one part of the video will be dedicated towards running a `.blink` file and another part will be dedicated to Running single expressions on the interpreter.

As for the interpreter and compiler, I think we should integrate both to make a new type of of compiling system. Perhaps the name would be something like Compreter or idk.

**Comment by ArrushC** [comment]
> Right now I am in school. After I come back, I will work on organisation a bit and generation. Perhaps I will do some documentation as well but it will be the guide/wiki.
> 
> Do you think making a video, guiding people on how to use Blink would be more efficient ?

As far as generation goes, I will make a separate folder, consisting of all the required files. In general having pre-defined `Stmt` and `Expr` files is much better than post-defined ones which is made via I/O management.

**Comment by Link-Byte** [comment]
Alright, if you can make those changes, test, compile and run the program without any issues, commit it.
