### ISSUE TITLE
Syntax Highlighting

### ISSUE THREAD

**Issue by Link-Byte** [BlinkLang/BlinkLang#2]
I know this can be bothersome. Not having syntax highlighting is somewhat of a deal-breaker. For that matter, I am creating a Visual Studio Code extension to add language highlight. This will be available in the "extensions" tab of VSC. If and when I close this issue, that means that the extension should be up by then

**Comment by ArrushC** [comment]
Other IDEs should also have an extension for blink so I will develop one for IntelliJ IDEA

**Comment by Link-Byte** [comment]
Awesome. The VSCode extension is being made and should be up pretty soon. Just need to finish some stuff. Thanks for making one for IntelliJ IDEA!
